### ISSUE TITLE
REQ: enable engines on/off from toolbar pop-up

### ISSUE THREAD

**Issue by EC-O-DE** [dessant/search-by-image#31] opened 2018-03-29 06:03 UTC
REQ: enable engines on/off from toolbar pop-up

Going to settings is sloow and painful.

**Comment by dessant** [comment] 2018-03-29 12:40
Duplicate of https://github.com/dessant/search-by-image/issues/24. Ref https://github.com/dessant/search-by-image/issues/9#issuecomment-342360487.

This has been suggested by you a couple of times already. You seem to want to model [PhotoTracker Lite](https://chrome.google.com/webstore/detail/phototracker-lite/opadloaiiilnjibkfkopaokgfkhggjgb), but the workflow of that extension is entirely different. You have to enable the engines you want to search with from the popup, and the search button will open tabs for all enabled engines. Searching with a single engine is only possible by turning off the rest, hence the need for constantly enabling and disabling search engines.

It would be best to contact the developer of PhotoTracker Lite regarding the privacy issues you've rised about it [here](https://github.com/dessant/search-by-image/issues/9#issuecomment-342360487), it seems what you really need is that extension.

**Closed by dessant** 2018-03-29 12:40 UTC
