### ISSUE TITLE
Pimeyes "Select" search mode support.

### ISSUE THREAD

**Issue by rampentWater** [dessant/search-by-image#103] opened 2020-12-02 04:54 UTC
**Is your feature request related to a problem? Please describe.**
Currently when trying to use the 'select' search mode with Pimeyes an error pops up.

**Describe the solution you'd like**
I'd like more than just the 'capture' search mode to be supported. (I think that's the only one that works.)

**Additional context**
It's a bummer that I can't use "search with all engines" due to Pimeyes erroring out.

**Comment by dessant** [comment] 2020-12-02 08:38
Are you using Chrome or a derivative? If the image is not found in the Select search mode, I suspect it is because of this bug: https://github.com/dessant/search-by-image/issues/102. I'm working on a solution.

**Comment by rampentWater** [comment] 2020-12-02 19:18
I was indeed using Chrome v87, however, just tried to do the same on Firefox v83 and I get the same issue.

Just for example, on twitter, [this photo](https://twitter.com/billieeilish/status/1329157832948662273/photo/1) fails to be able to be searched on both Firefox and Chrome with Pimeyes `Select `mode.

Right clicking the image and selecting PimEyes results in a `No image found. Try searching again by placing the cursor above the image.` notification in both browsers. However searching the example with Google, on `Select` mode still, results in a successful outcome.

To note! If I view only this image in a new tab, everything works in both browsers.

**Comment by dessant** [comment] 2020-12-02 20:03
I can reproduce the issue on Chrome 87 with your tweet, but Firefox 83 works as expected.

**Comment by dessant** [comment] 2020-12-02 20:07
Maybe you've configured Firefox differently, or they have remotely enabled some experimental feature for your profile. All test cases shared in #102 work as expected on Firefox and Linux.

**Comment by rampentWater** [comment] 2020-12-03 06:04
You were correct! New Firefox profile worked fine. A little bit of sleuthing shows that setting Firefox's "Enhanced Tracking Protection" to `strict` rather than the default `standard` results in the issue. Configurable at `about:preferences#privacy`.

For now I'm happy working around the issue, so thank you very much for that! Good luck on #102.

**Comment by dessant** [comment] 2020-12-07 04:49
The issue should be fixed in https://github.com/dessant/search-by-image/commit/020ba13a9c8178243bb5861f78973b4b5b425175, a new release will come probably tomorrow.

**Closed by dessant** 2020-12-07 04:49 UTC
