### ISSUE TITLE
Context menu appears when no image is right clicked

### ISSUE THREAD

**Issue by jedikalimero** [dessant/search-by-image#23] opened 2018-01-24 01:57 UTC
This add on is meant to work with the image that the user right clicks, but it appears always in the context menu even if there is no image under the mouse pointer, what makes no sense. It should appear only when the mouse pointer is over an image.

**Comment by dessant** [comment] 2018-01-24 02:35
Duplicate of https://github.com/dessant/search-by-image/issues/22 and https://github.com/dessant/search-by-image/issues/14#issuecomment-348826094.

**Closed by dessant** 2018-01-24 02:35 UTC
